version: "3.3"

networks:
  default:

services:
#  app-api:
#    build:
#      context: ./api
#    image: test-moto-api
#    ports:
#      - 3000:3000
#    volumes:
#      - /app/dist
#      - /app/node_modules
#      - ./api:/app
#    env_file:
#      - ./api/.env
#    command: "npm run start:dev"

  app-web:
    build:
      context: ./web
    image: test-moto-web
    ports:
      - 8000:8000
    volumes:
      - /app/build
      - /app/node_modules
      - ./web:/app
    env_file:
      - ./web/.env
    command: "npm run start"
